schema: 1
base: "1.0"

components:
  H0:
    status: installed
  H1:
    status: installed
    profiles:
      node-typescript:
        status: installed
        scopes:
          - "."
  H2:
    status: installed
    profiles:
      node-typescript:
        status: installed
        scopes:
          - "."
  H3:
    status: installed
  H4:
    status: not-installed
  H5:
    status: installed
  H6:
    status: not-installed
  H7:
    status: not-installed
  X:
    status: installed
